// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/todoitem.proto

/*
Package todolist is a generated protocol buffer package.

It is generated from these files:
	proto/todoitem.proto

It has these top-level messages:
	ToDoItem
	ID
	Nothing
	ToDoList
	UpdatedItem
*/
package todolist

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ToDoItem struct {
	Id          uint32 `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=Description" json:"Description,omitempty"`
	IsDone      bool   `protobuf:"varint,4,opt,name=IsDone" json:"IsDone,omitempty"`
}

func (m *ToDoItem) Reset()                    { *m = ToDoItem{} }
func (m *ToDoItem) String() string            { return proto.CompactTextString(m) }
func (*ToDoItem) ProtoMessage()               {}
func (*ToDoItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ToDoItem) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ToDoItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ToDoItem) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ToDoItem) GetIsDone() bool {
	if m != nil {
		return m.IsDone
	}
	return false
}

type ID struct {
	Id uint32 `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
}

func (m *ID) Reset()                    { *m = ID{} }
func (m *ID) String() string            { return proto.CompactTextString(m) }
func (*ID) ProtoMessage()               {}
func (*ID) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ID) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Nothing struct {
}

func (m *Nothing) Reset()                    { *m = Nothing{} }
func (m *Nothing) String() string            { return proto.CompactTextString(m) }
func (*Nothing) ProtoMessage()               {}
func (*Nothing) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type ToDoList struct {
	ToDoList []*ToDoItem `protobuf:"bytes,1,rep,name=ToDoList" json:"ToDoList,omitempty"`
}

func (m *ToDoList) Reset()                    { *m = ToDoList{} }
func (m *ToDoList) String() string            { return proto.CompactTextString(m) }
func (*ToDoList) ProtoMessage()               {}
func (*ToDoList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ToDoList) GetToDoList() []*ToDoItem {
	if m != nil {
		return m.ToDoList
	}
	return nil
}

type UpdatedItem struct {
	UpdateTodo *ToDoItem `protobuf:"bytes,1,opt,name=UpdateTodo" json:"UpdateTodo,omitempty"`
	UpdateID   *ID       `protobuf:"bytes,2,opt,name=updateID" json:"updateID,omitempty"`
}

func (m *UpdatedItem) Reset()                    { *m = UpdatedItem{} }
func (m *UpdatedItem) String() string            { return proto.CompactTextString(m) }
func (*UpdatedItem) ProtoMessage()               {}
func (*UpdatedItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *UpdatedItem) GetUpdateTodo() *ToDoItem {
	if m != nil {
		return m.UpdateTodo
	}
	return nil
}

func (m *UpdatedItem) GetUpdateID() *ID {
	if m != nil {
		return m.UpdateID
	}
	return nil
}

func init() {
	proto.RegisterType((*ToDoItem)(nil), "todolist.ToDoItem")
	proto.RegisterType((*ID)(nil), "todolist.ID")
	proto.RegisterType((*Nothing)(nil), "todolist.Nothing")
	proto.RegisterType((*ToDoList)(nil), "todolist.ToDoList")
	proto.RegisterType((*UpdatedItem)(nil), "todolist.UpdatedItem")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ToDoActions service

type ToDoActionsClient interface {
	GetItems(ctx context.Context, in *Nothing, opts ...grpc.CallOption) (*ToDoList, error)
	AddItem(ctx context.Context, in *ToDoItem, opts ...grpc.CallOption) (*ToDoItem, error)
	GetItem(ctx context.Context, in *ID, opts ...grpc.CallOption) (*ToDoItem, error)
	DeleteItem(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Nothing, error)
	UpdateItem(ctx context.Context, in *UpdatedItem, opts ...grpc.CallOption) (*Nothing, error)
}

type toDoActionsClient struct {
	cc *grpc.ClientConn
}

func NewToDoActionsClient(cc *grpc.ClientConn) ToDoActionsClient {
	return &toDoActionsClient{cc}
}

func (c *toDoActionsClient) GetItems(ctx context.Context, in *Nothing, opts ...grpc.CallOption) (*ToDoList, error) {
	out := new(ToDoList)
	err := grpc.Invoke(ctx, "/todolist.ToDoActions/GetItems", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toDoActionsClient) AddItem(ctx context.Context, in *ToDoItem, opts ...grpc.CallOption) (*ToDoItem, error) {
	out := new(ToDoItem)
	err := grpc.Invoke(ctx, "/todolist.ToDoActions/AddItem", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toDoActionsClient) GetItem(ctx context.Context, in *ID, opts ...grpc.CallOption) (*ToDoItem, error) {
	out := new(ToDoItem)
	err := grpc.Invoke(ctx, "/todolist.ToDoActions/GetItem", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toDoActionsClient) DeleteItem(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Nothing, error) {
	out := new(Nothing)
	err := grpc.Invoke(ctx, "/todolist.ToDoActions/DeleteItem", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toDoActionsClient) UpdateItem(ctx context.Context, in *UpdatedItem, opts ...grpc.CallOption) (*Nothing, error) {
	out := new(Nothing)
	err := grpc.Invoke(ctx, "/todolist.ToDoActions/UpdateItem", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ToDoActions service

type ToDoActionsServer interface {
	GetItems(context.Context, *Nothing) (*ToDoList, error)
	AddItem(context.Context, *ToDoItem) (*ToDoItem, error)
	GetItem(context.Context, *ID) (*ToDoItem, error)
	DeleteItem(context.Context, *ID) (*Nothing, error)
	UpdateItem(context.Context, *UpdatedItem) (*Nothing, error)
}

func RegisterToDoActionsServer(s *grpc.Server, srv ToDoActionsServer) {
	s.RegisterService(&_ToDoActions_serviceDesc, srv)
}

func _ToDoActions_GetItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Nothing)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToDoActionsServer).GetItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todolist.ToDoActions/GetItems",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToDoActionsServer).GetItems(ctx, req.(*Nothing))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToDoActions_AddItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToDoItem)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToDoActionsServer).AddItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todolist.ToDoActions/AddItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToDoActionsServer).AddItem(ctx, req.(*ToDoItem))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToDoActions_GetItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToDoActionsServer).GetItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todolist.ToDoActions/GetItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToDoActionsServer).GetItem(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToDoActions_DeleteItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToDoActionsServer).DeleteItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todolist.ToDoActions/DeleteItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToDoActionsServer).DeleteItem(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToDoActions_UpdateItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatedItem)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToDoActionsServer).UpdateItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todolist.ToDoActions/UpdateItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToDoActionsServer).UpdateItem(ctx, req.(*UpdatedItem))
	}
	return interceptor(ctx, in, info, handler)
}

var _ToDoActions_serviceDesc = grpc.ServiceDesc{
	ServiceName: "todolist.ToDoActions",
	HandlerType: (*ToDoActionsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetItems",
			Handler:    _ToDoActions_GetItems_Handler,
		},
		{
			MethodName: "AddItem",
			Handler:    _ToDoActions_AddItem_Handler,
		},
		{
			MethodName: "GetItem",
			Handler:    _ToDoActions_GetItem_Handler,
		},
		{
			MethodName: "DeleteItem",
			Handler:    _ToDoActions_DeleteItem_Handler,
		},
		{
			MethodName: "UpdateItem",
			Handler:    _ToDoActions_UpdateItem_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/todoitem.proto",
}

func init() { proto.RegisterFile("proto/todoitem.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 370 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0xc1, 0x6a, 0xea, 0x40,
	0x14, 0x35, 0x51, 0x34, 0xde, 0xbc, 0xf7, 0xe0, 0x5d, 0x7c, 0x12, 0xdc, 0xbc, 0x30, 0x8b, 0x92,
	0x8d, 0x09, 0xc4, 0x4d, 0x71, 0x67, 0x09, 0x94, 0x40, 0x71, 0x11, 0xec, 0xba, 0xa8, 0x99, 0xc6,
	0x41, 0xe3, 0x0d, 0xc9, 0xb8, 0x70, 0xd7, 0x5f, 0xe8, 0x0f, 0xf6, 0x23, 0xfa, 0x05, 0x25, 0x13,
	0x35, 0xb6, 0x4d, 0x77, 0xf7, 0xcc, 0x9c, 0x73, 0xcf, 0x39, 0xc3, 0xc0, 0x20, 0xcb, 0x49, 0x92,
	0x27, 0x29, 0x26, 0x21, 0x79, 0xea, 0x2a, 0x88, 0x46, 0x89, 0x77, 0xa2, 0x90, 0xa3, 0x71, 0x22,
	0xe4, 0xe6, 0xb0, 0x72, 0xd7, 0x94, 0x7a, 0x09, 0x25, 0xe4, 0x29, 0xc2, 0xea, 0xf0, 0xac, 0x50,
	0x25, 0x2e, 0xa7, 0x4a, 0xc8, 0x5e, 0x34, 0x30, 0x16, 0x14, 0x50, 0x28, 0x79, 0x8a, 0x37, 0xa0,
	0x87, 0xb1, 0xa5, 0xd9, 0x9a, 0xf3, 0xfb, 0x6e, 0xf8, 0xfe, 0xf6, 0x1f, 0x13, 0xca, 0xd3, 0x29,
	0xcb, 0x72, 0x91, 0x2e, 0xf3, 0xe3, 0xd3, 0x96, 0x1f, 0x59, 0xa4, 0x87, 0x31, 0x22, 0x74, 0xe6,
	0xcb, 0x94, 0x5b, 0xba, 0xad, 0x39, 0xfd, 0x48, 0xcd, 0x68, 0x83, 0x19, 0xf0, 0x62, 0x9d, 0x8b,
	0x4c, 0x0a, 0xda, 0x5b, 0x6d, 0x75, 0x75, 0x7d, 0x84, 0x43, 0xe8, 0x86, 0x45, 0x40, 0x7b, 0x6e,
	0x75, 0x6c, 0xcd, 0x31, 0xa2, 0x13, 0x62, 0x03, 0xd0, 0xc3, 0x00, 0xff, 0xd4, 0xde, 0xa5, 0x07,
	0xeb, 0x43, 0x6f, 0x4e, 0x72, 0x23, 0xf6, 0x09, 0x9b, 0x56, 0x11, 0x1f, 0x44, 0x21, 0xd1, 0xad,
	0x67, 0x4b, 0xb3, 0xdb, 0x8e, 0xe9, 0xa3, 0x7b, 0xee, 0xee, 0x9e, 0x8b, 0x44, 0x17, 0x0e, 0xdb,
	0x82, 0xf9, 0x98, 0xc5, 0x4b, 0xc9, 0x63, 0xd5, 0xd0, 0x07, 0xa8, 0xe0, 0x82, 0x62, 0x52, 0x6e,
	0xcd, 0x0b, 0xae, 0x58, 0xe8, 0x80, 0x71, 0x50, 0x28, 0x0c, 0x54, 0x63, 0xd3, 0xff, 0x55, 0x2b,
	0xc2, 0x20, 0xba, 0xdc, 0xfa, 0xaf, 0x3a, 0x98, 0xe5, 0x8a, 0xd9, 0xba, 0x2c, 0x5c, 0xe0, 0x04,
	0x8c, 0x7b, 0x2e, 0xcb, 0x85, 0x05, 0xfe, 0xad, 0x35, 0xa7, 0x5e, 0xa3, 0x2f, 0xc6, 0x2a, 0x6f,
	0x0b, 0x27, 0xd0, 0x9b, 0xc5, 0x55, 0xda, 0x86, 0x64, 0xa3, 0x86, 0x33, 0xd6, 0xc2, 0x31, 0xf4,
	0x4e, 0x4e, 0xf8, 0x29, 0xdc, 0x0f, 0x74, 0x0f, 0x20, 0xe0, 0x3b, 0x2e, 0x79, 0x83, 0xe2, 0x7b,
	0x50, 0xd6, 0xc2, 0xdb, 0xf3, 0xbb, 0x29, 0xc1, 0xbf, 0x9a, 0x72, 0xf5, 0xb8, 0x8d, 0xca, 0x55,
	0x57, 0xfd, 0xb3, 0xc9, 0x47, 0x00, 0x00, 0x00, 0xff, 0xff, 0x17, 0x0b, 0xff, 0x12, 0xb8, 0x02,
	0x00, 0x00,
}
